### ISSUE TITLE
Reprocess `webc:type="render"` output as WebC

### ISSUE THREAD

**Issue by Gyanreyer** [11ty/webc#33]
It seems that I'm unable to render other components from a render script component.

To reproduce, I have these two components:
`components/link.webc`:
```html
<a :href="this.href"><slot></slot></a>
```
`components/project.webc`:
```html
<script webc:type="render" webc:is="template">
function(){
  return `
    <div>
      <h3>This is a project</h3>
      <text-link href="/project">Check it out</text-link>
    </div>
  `;
}
</script>
```

The output for the `<project>` component in this case will be:
```html
<div>
    <h3>This is a project</h3>
    <text-link href="/project">Check it out</text-link>
</div>
```

But I would have expected the `text-link` component to have been transformed like so:
```html
<div>
    <h3>This is a project</h3>
    <a href="/project">Check it out"</a>
</div>
```

It's very possible that I'm just mis-using something, but wanted to make sure it's not a bug!

**Comment by kleinfreund** [comment]
I wrote a regression test for this and confirm that this currently fails to resolve as expected.

## Test case

**test/parserTest.js**:

```javascript
test("Script component resolves child component", async (t) => {
	let component = new WebC();
	component.setInputPath("./test/stubs/render-child-component.webc");
	component.defineComponents({ "text-link": "./test/stubs/components/text-link-slot.webc" });

	let { html } = await component.compile();

	t.is(html, `<h3>Title</h3>
<a href="/project">Link text</a>`);
});
```

**test/stubs/render-child-component.webc**:

```html
<script webc:type="render" webc:is="template">
function() {
	return `<h3>Title</h3>
<text-link href="/project">Link text</text-link>`;
}
</script>
```

**test/stubs/components/text-link-slot.webc**:

```html
<a :href="this.href"><slot>Default link text</slot></a>
```

**Fail**:

```
  Script component resolves child component

  test\parserTest.js:1863

   1862:
   1863:   t.is(html, `<h3>Title</h3>       
   1864: <a href="/project">Link text</a>`);

  Difference:

    `<h3>Title</h3>␊
  - <text-link href="/project">Link text</text-link>`
  + <a href="/project">Link text</a>`
```

**Comment by zachleat** [comment]
Yeah @philhawksworth asked me about this too, whether we should reprocess `<template webc:type="render">` output as webc!

I do consider this an enhancement request rather than a bug, but I think folks might expect it moving forward—given the questions I’ve gotten so far!

**Comment by zachleat** [comment]
Marginally related to https://github.com/11ty/webc/issues/16 too

**Comment by darthmall** [comment]
I have no objection to the enhancement/bug distinction, but I do think it’s important to be able to compose WebC components from inside a render function.

I don’t think it _has_ to mean reprocessing the return value of a render function through WebC — although this does seem like the most convenient way for the developer. It could be something that you opt into inside the render function so that WebC knows, when it’s executing the render function, that it needs to expand these tags. Perhaps a simple `webc:` attribute that WebC could scan the output for so it doesn’t have to process everything.

Or maybe a way to render the expanded tags in JavaScript so that the returned value from the render function is already expanded. I’d be ok with something like:

```html
<ul>
  <script webc:type="render" webc:is="template">
    // Get a programmatic way of generating the markup for a component
    import cardComp from "./card-comp.webc";

    function () {
      return this.someArray.map((item) => {
        // Do something with `item`
        return `<li>
          ${cardComp(attrs, props, content)}
        </li>`
      }).join("");      
    }
  </script>
</ul>
```

**Comment by kleinfreund** [comment]
@darthmall Spinning this further, I think some rudiments of the kind of API that you;re thinking of are present in the following form:

```html
<ul>
  <script webc:type="render" webc:is="template">
    import { WebC } from "@11ty/webc";

    let page = new WebC();
    page.setInputPath("./card-comp.webc");
    let { cardCompHtml } = await page.compile()

    function () {
      return this.someArray.map((item) => {
        // Do something with `item`
        return `<li>
          ${cardCompHtml}
        </li>`
      }).join("");      
    }
  </script>
</ul>
```

What's left is how to dynamically pass in attributes, props, slot content, etc.

> It could be something that you opt into inside the render function so that WebC knows, when it’s executing the render function, that it needs to expand these tags. Perhaps a simple webc: attribute that WebC could scan the output for so it doesn’t have to process everything.

I think it would be the least overall friction (and frankly ingenious) if everything by default can simply be processed as WebC because, well, it's just HTML, right? Special things like scoped styles, etc. will need opt-ins, but by default, processing an arbitrary HTML tree by WebC should just work™️.

**Comment by kleinfreund** [comment]
Also, in the interest of being explicit, I'd like to see **the** render function in the following to require because default exported so that in the presence of multiple top-level functions in the script, there is no ambiguity:

```html
<script webc:type="render" webc:is="template">
function generateMyStuff() {
	if(!this.alt) {
		throw new Error("oh no you didn’t");
	}
	// Free idea: use the Eleventy Image plugin to return optimized markup
	return `<img src="${this.src}" alt="${this.alt}">`;
}

export default function() {
	return generateMyStuff();
}
</script>
```

**Comment by zachleat** [comment]
Thanks to the PR #34 from @kleinfreund content from `<template webc:type>` and `<* webc:is="template" webc:type>` nodes will be processed as WebC!

Shipping with 0.5.0
